"""Tests for the static HTML decision-log report."""
from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from report_html import build_report, write_report  # noqa: E402
from state import RunState  # noqa: E402

LAYOUT_SVG = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Qucs-RFlayout from : circuit.sch -->
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 20 20" width="5mm" height="5mm">
  <path id="MSW1" d="M0 0 L1 1 Z" fill="black" stroke="none"/>
</svg>
"""


def _cost(total: float) -> dict:
    return {
        "total_cost": total,
        "target_freq_hz": 5.5e9,
        "target_s21_mag": total,
        "mean_cost": total,
        "low_edge_cost": total,
        "center_cost": total,
        "high_edge_cost": total,
        "stopband_max_s21": total,
        "worst_freq_hz": 6e9,
        "best_freq_hz": 5.5e9,
        "best_s21_mag": total,
        "passband_low_mean": 0.5,
        "passband_high_mean": 0.5,
        "zin_norm_at_center": 1.0,
        "band_hz": [4e9, 6e9],
    }


def _history() -> list[dict]:
    return [
        {
            "iteration": 0,
            "params": {"ri": 0.3, "ro": 8.0, "alpha": 90.0, "Wf": 0.6, "Lc": 3.0},
            "cost": _cost(0.28),
            "intent": None,
            "note": "baseline",
            "thinking": "",
            "observation": None,
        },
        {
            "iteration": 1,
            "params": {"ri": 0.3, "ro": 5.95, "alpha": 90.0, "Wf": 0.6, "Lc": 3.0},
            "cost": _cost(0.01),
            "intent": {"ro": "decrease_strong"},
            "note": "shrink ro",
            "thinking": "The notch sits at 3.3 GHz, far below target; shrink ro hard.",
            "observation": {"from_iteration": 0, "report_text": "--- iteration 0 ---"},
        },
    ]


class BuildReportTests(unittest.TestCase):
    def setUp(self):
        self._td = tempfile.TemporaryDirectory()
        self.run_dir = Path(self._td.name)
        for it in (0, 1):
            d = self.run_dir / f"iter_{it:03d}"
            d.mkdir()
            (d / "layout.svg").write_text(LAYOUT_SVG)

    def tearDown(self):
        self._td.cleanup()

    def test_one_collapsible_panel_per_iteration(self):
        html = build_report("demo", self.run_dir, _history())
        self.assertEqual(html.count('<details class="iter'), 2)
        self.assertIn('id="iter-000"', html)
        self.assertIn('id="iter-001"', html)

    def test_panel_carries_observation_thinking_and_intent(self):
        html = build_report("demo", self.run_dir, _history())
        self.assertIn("--- iteration 0 ---", html)
        self.assertIn("The notch sits at 3.3 GHz", html)
        self.assertIn("decrease_strong", html)

    def test_missing_reasoning_degrades_to_placeholder(self):
        history = _history()
        history[1]["thinking"] = ""
        html = build_report("demo", self.run_dir, history)
        self.assertIn("no full reasoning recorded", html)

    def test_layout_svg_is_inlined_without_fixed_size(self):
        html = build_report("demo", self.run_dir, _history())
        self.assertIn('id="MSW1"', html)
        self.assertNotIn('width="5mm"', html)
        self.assertIn('viewBox="0 0 20 20"', html)

    def test_best_iteration_is_marked(self):
        html = build_report("demo", self.run_dir, _history())
        self.assertIn('<span class="badge best">best</span>', html)

    def test_thinking_is_html_escaped(self):
        history = _history()
        history[1]["thinking"] = "notch <script>alert(1)</script> & drift"
        html = build_report("demo", self.run_dir, history)
        self.assertNotIn("<script>alert(1)</script>", html)
        self.assertIn("&lt;script&gt;", html)

    def test_write_report_creates_file(self):
        out = self.run_dir / "report.html"
        write_report("demo", self.run_dir, _history(), out)
        self.assertTrue(out.exists())
        self.assertIn("<!DOCTYPE html>", out.read_text())


def _bpf_cost(**overrides) -> dict:
    base = {
        "total_cost": 0.42,
        "passband_min_s21_db": -0.8,
        "stopband_max_s21_db": -22.0,
        "passband_mean_s21_db": -0.5,
        "s11_passband_max_db": -12.0,
        "has_passband_samples": True,
        "has_stopband_samples": True,
        "f_low_hz": 135e6,
        "f_high_hz": 165e6,
    }
    base.update(overrides)
    return base


def _bpf_history() -> list[dict]:
    params0 = {
        "L1": 160.0, "C1": 7.0, "L2": 6.5, "C2": 170.0, "L3": 530.0,
        "C3": 2.1, "L4": 6.5, "C4": 170.0, "L5": 160.0, "C5": 7.0,
    }
    params1 = dict(params0, L3=500.0, C3=2.3)
    return [
        {
            "iteration": 0,
            "params": params0,
            "cost": _bpf_cost(total_cost=0.5, passband_min_s21_db=-1.2),
            "intent": None,
            "note": "baseline",
            "thinking": "",
            "observation": None,
        },
        {
            "iteration": 1,
            "params": params1,
            "cost": _bpf_cost(total_cost=0.3, passband_min_s21_db=-0.6),
            "intent": {"L3": "decrease", "C3": "increase"},
            "note": "tune L3/C3",
            "thinking": "passband IL high; adjust series resonator",
            "observation": {"from_iteration": 0, "report_text": "--- bpf iter 0 ---"},
        },
    ]


class BpfReportTests(unittest.TestCase):
    def setUp(self):
        self._td = tempfile.TemporaryDirectory()
        self.run_dir = Path(self._td.name)
        for it in (0, 1):
            (self.run_dir / f"iter_{it:03d}").mkdir()
            # No layout.svg — lumped BPF skips qucsrflayout.

    def tearDown(self):
        self._td.cleanup()

    def test_write_report_bpf_without_layout_succeeds(self):
        out = self.run_dir / "report.html"
        write_report(
            "bpf_demo",
            self.run_dir,
            _bpf_history(),
            out,
            task="butterworth_bpf5",
        )
        html = out.read_text()
        self.assertIn("<!DOCTYPE html>", html)
        self.assertIn("passband_min_s21_db", html)
        self.assertIn("total_cost", html)
        self.assertIn("no layout.svg", html)
        self.assertIn("L3", html)

    def test_build_report_detects_bpf_cost_keys(self):
        html = build_report("bpf_demo", self.run_dir, _bpf_history())
        self.assertIn("passband_min_s21_db", html)
        self.assertIn("total_cost", html)


class StateThinkingTests(unittest.TestCase):
    def test_record_persists_thinking_and_observation(self):
        with tempfile.TemporaryDirectory() as td:
            state = RunState(Path(td))
            state.record({"ro": 8.0}, _cost(0.2), None, "baseline")
            state.record(
                {"ro": 6.0},
                _cost(0.1),
                {"ro": "decrease"},
                "shrink",
                thinking="notch too low",
                observation={"from_iteration": 0, "report_text": "block"},
            )
            reloaded = RunState(Path(td))
            entry = reloaded.history[1]
        self.assertEqual(entry["thinking"], "notch too low")
        self.assertEqual(entry["observation"]["from_iteration"], 0)

    def test_thinking_defaults_to_empty(self):
        with tempfile.TemporaryDirectory() as td:
            state = RunState(Path(td))
            state.record({"ro": 8.0}, _cost(0.2), None, "baseline")
            self.assertEqual(state.history[0]["thinking"], "")
            self.assertIsNone(state.history[0]["observation"])


if __name__ == "__main__":
    unittest.main()
