"""Tests for Qucs-RFlayout-backed layout export."""
from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from intent import INITIAL_GUESS  # noqa: E402
from qucs_sim import (  # noqa: E402
    export_layout_svg,
    render_schematic,
    resolve_qucsrflayout,
)


def _has_layout_tools() -> bool:
    from qucs_sim import resolve_qucs_s

    try:
        resolve_qucs_s()
        resolve_qucsrflayout()
        return True
    except FileNotFoundError:
        return False


class ResolveQucsRflayoutTests(unittest.TestCase):
    def test_resolve_finds_third_party_or_env_binary(self):
        path = resolve_qucsrflayout()
        self.assertTrue(Path(path).exists())


@unittest.skipUnless(_has_layout_tools(), "qucs-s / qucsrflayout not available")
class QucsRflayoutExportTests(unittest.TestCase):
    def test_export_layout_svg_writes_rflayout_marker(self):
        sch = render_schematic(
            dict(INITIAL_GUESS),
            f0_hz=5e9,
            sweep_start_hz=1e9,
            sweep_stop_hz=10e9,
            sweep_points=21,
        )
        with tempfile.TemporaryDirectory() as td:
            workdir = Path(td)
            sch_path = workdir / "circuit.sch"
            sch_path.write_text(sch)
            from qucs_sim import export_netlist_from_sch

            net_path = export_netlist_from_sch(sch_path, workdir / "circuit.net")
            svg_path = export_layout_svg(sch_path, net_path, workdir / "layout.svg")
            text = svg_path.read_text()
        self.assertIn("Generated by Qucs-RFlayout", text)
        self.assertIn('id="MSW1"', text)
        self.assertIn('id="MSW2"', text)
        self.assertIn('id="MLin"', text)
        self.assertIn('id="MLout"', text)
        self.assertIn('id="J1"', text)


if __name__ == "__main__":
    unittest.main()
