"""Tests for schematic-first Qucs simulation pipeline."""
from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from intent import INITIAL_GUESS  # noqa: E402
from qucs_sim import (  # noqa: E402
    export_netlist_from_sch,
    render_schematic,
    simulate,
)


def _has_qucs_tools() -> bool:
    from qucs_sim import resolve_qucs_s, resolve_qucsator

    try:
        resolve_qucs_s()
        resolve_qucsator()
        return True
    except FileNotFoundError:
        return False


@unittest.skipUnless(_has_qucs_tools(), "qucs-s / qucsator_rf not available")
class SchematicPipelineTests(unittest.TestCase):
    def test_render_schematic_is_two_port(self):
        text = render_schematic(
            {"ri": 0.51, "ro": 3.0, "alpha": 99.1, "Wf": 0.6, "Lc": 2.78},
            f0_hz=5e9,
            sweep_start_hz=1e9,
            sweep_stop_hz=10e9,
            sweep_points=181,
        )
        self.assertIn("<Qucs Schematic", text)
        self.assertIn('Pac P1 ', text)
        self.assertIn('Pac P2 ', text)
        self.assertIn('"1"', text)
        self.assertIn('"2"', text)
        self.assertIn("MLIN MLin", text)
        self.assertIn("MLIN MLout", text)
        self.assertIn("MCROSS J1", text)
        self.assertIn("MRSTUB MSW1", text)
        self.assertIn("MRSTUB MSW2", text)
        self.assertIn(
            '"Subst1" 0 "0.51mm" 1 "3.0mm" 1 "0.6mm" 1 "99.1"',
            text,
        )
        self.assertIn("S21_dB=dB(S[2,1])", text)
        self.assertIn("S21_phase=phase(S[2,1])", text)
        self.assertIn("<Rect ", text)
        self.assertIn("<Smith ", text)
        self.assertIn("<Polar ", text)
        self.assertIn('"Zin_norm"', text)
        self.assertIn('"S11_dB"', text)
        self.assertIn('"S21_dB"', text)
        self.assertIn('"S11_phase"', text)
        self.assertIn('"S21_phase"', text)
        self.assertIn('"S[1,1]"', text)
        self.assertIn('"S[2,1]"', text)
        self.assertGreaterEqual(text.count("<Polar "), 2)

    def test_sch_exports_two_port_netlist_with_mcross_junction(self):
        sch = render_schematic(
            dict(INITIAL_GUESS),
            f0_hz=5e9,
            sweep_start_hz=1e9,
            sweep_stop_hz=10e9,
            sweep_points=181,
        )
        with tempfile.TemporaryDirectory() as td:
            workdir = Path(td)
            sch_path = workdir / "circuit.sch"
            sch_path.write_text(sch)
            net_path = export_netlist_from_sch(sch_path, workdir / "circuit.net")
            net = net_path.read_text()
        self.assertIn("Pac:P1", net)
        self.assertIn("Pac:P2", net)
        self.assertIn("MLIN:MLin", net)
        self.assertIn("MLIN:MLout", net)
        self.assertIn("MCROSS:J1", net)
        self.assertIn("MRSTUB:MSW1", net)
        self.assertIn("MRSTUB:MSW2", net)
        j1 = [ln for ln in net.splitlines() if ln.startswith("MCROSS:J1")][0]
        ports = j1.split()[1:5]
        self.assertEqual(len(set(ports)), 4)
        mlin_in = [ln for ln in net.splitlines() if ln.startswith("MLIN:MLin")][0]
        mlin_out = [ln for ln in net.splitlines() if ln.startswith("MLIN:MLout")][0]
        s1 = [ln for ln in net.splitlines() if ln.startswith("MRSTUB:MSW1")][0]
        s2 = [ln for ln in net.splitlines() if ln.startswith("MRSTUB:MSW2")][0]
        self.assertIn(mlin_in.split()[2], ports)
        self.assertIn(mlin_out.split()[1], ports)
        self.assertIn(s1.split()[1], ports)
        self.assertIn(s2.split()[1], ports)
        self.assertIn('ri="0.3mm"', net)
        self.assertIn("S21_dB=", net)

    def test_simulate_writes_two_port_equation_vars(self):
        with tempfile.TemporaryDirectory() as td:
            workdir = Path(td)
            simulate(dict(INITIAL_GUESS), workdir=workdir)
            dat = (workdir / "circuit.dat").read_text()
        for name in (
            "Zin_norm",
            "Zin_ohm",
            "S11_phase",
            "S21_phase",
            "S11_dB",
            "S21_dB",
            "S[1,1]",
            "S[2,1]",
        ):
            self.assertIn(name, dat)

    def test_simulate_initial_guess_two_port_cost_baseline(self):
        with tempfile.TemporaryDirectory() as td:
            workdir = Path(td)
            res = simulate(dict(INITIAL_GUESS), workdir=workdir)
            self.assertTrue((workdir / "circuit.sch").exists())
            self.assertTrue((workdir / "circuit.net").exists())
            self.assertTrue((workdir / "circuit.dat").exists())
            layout = workdir / "layout.svg"
            self.assertTrue(layout.exists())
            self.assertIn("Generated by Qucs-RFlayout", layout.read_text())
            sch = (workdir / "circuit.sch").read_text()
            self.assertIn("Pac P2", sch)
            self.assertIn("MCROSS J1", sch)
        from cost import evaluate

        cost = evaluate(res, (4e9, 6e9)).total_cost
        # MCROSS discontinuity shifts the notch vs wire-only junction.
        self.assertGreater(cost, 0.05)
        self.assertLess(cost, 0.95)

    def test_simulate_can_skip_layout_export_for_training(self):
        with tempfile.TemporaryDirectory() as td:
            workdir = Path(td)
            res = simulate(
                dict(INITIAL_GUESS),
                workdir=workdir,
                export_layout=False,
            )
            self.assertFalse((workdir / "layout.svg").exists())
            self.assertEqual(len(res.freq_hz), 181)
            self.assertEqual(len(res.s21), 181)


if __name__ == "__main__":
    unittest.main()
